name: Build and Release ForceBindIP GUI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: [ubuntu-latest]
    if: ${{ !contains(github.event.head_commit.message, '[skip-ci]') }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Get short SHA
        id: get_short_sha
        if: ${{ !contains(github.event.head_commit.message, '[release]') }}
        run: echo "::set-output name=short_sha::$(echo ${{ github.sha }} | cut -c1-10)"

      - name: Get current date and time
        id: get_date
        if: ${{ !contains(github.event.head_commit.message, '[release]') }}
        run: |
          utc_date=$(TZ='UTC' date +'%Y-%m-%d @ %H:%M:%S')
          echo "::set-output name=date::$utc_date"

      - name: Write build details to file
        if: ${{ !contains(github.event.head_commit.message, '[release]') }}
        run: |
          printf "%s\n%s" "${{ steps.get_date.outputs.date }}" "${{ steps.get_short_sha.outputs.short_sha }}" > build_details.txt

      - name: Package Application
        uses: JackMcKew/pyinstaller-action-windows@main
        with:
          path: .

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ForceBindIPGUI
          path: dist/windows/ForceBindIP-GUI.exe

  release:
    runs-on: [ubuntu-latest]
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ForceBindIPGUI
          path: ./dist

      - name: Get short SHA
        id: get_short_sha
        run: echo "::set-output name=short_sha::$(echo ${{ github.sha }} | cut -c1-10)"

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: cicd-${{ github.run_number }}
          name: cicd-${{ steps.get_short_sha.outputs.short_sha }}
          body: |
            Release triggered by commit [${{ steps.get_short_sha.outputs.short_sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }}): ${{ github.event.head_commit.message }}            
          files: ./dist/ForceBindIP-GUI.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run latest-tag
        uses: EndBug/latest-tag@latest
        with:
          ref: latest
          description: |
            Latest release - triggered by commit [${{ steps.get_short_sha.outputs.short_sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }})
          force-branch: false
          git-directory: '.'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
